import { config } from 'dotenv';
import { app, BrowserWindow, dialog, ipcMain, Menu, nativeTheme, shell } from 'electron';
import { installExtension, REACT_DEVELOPER_TOOLS, REDUX_DEVTOOLS } from 'electron-devtools-installer';
import { existsSync, unlinkSync, writeFileSync } from 'fs';
import path from 'path';
import {
  loadSettings,
  registerCertificateHandlers,
  registerCliHandlers,
  registerCollectionHandlers,
  registerEnvironmentHandlers,
  registerHistoryHandlers,
  registerHttpHandlers,
  registerImportExportHandlers,
  registerMappingsHandlers,
  registerProjectHandlers,
  registerSettingsHandlers,
  registerWssHandlers,
} from './handlers';

config();

process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// eslint-disable-next-line @typescript-eslint/no-require-imports
if (require('electron-squirrel-startup')) app.quit();

function cleanupLegacyStore(): void {
  try {
    const userDataPath = app.getPath('userData');
    const legacyFile = path.join(userDataPath, 'config.json');

    if (existsSync(legacyFile)) {
      unlinkSync(legacyFile);
      console.log('Cleaned up legacy electron-store file');
    }
  } catch (error) {
    console.error('Failed to cleanup legacy store:', error);
  }
}

const createWindow = async (): Promise<void> => {
  const icon =
    process.platform === 'win32'
      ? './assets/icons/rentgen.ico'
      : process.platform === 'linux'
        ? './assets/icons/rentgen.png'
        : undefined;

  // Create the browser window.
  const mainWindow = new BrowserWindow({
    icon,
    show: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  mainWindow.maximize();
  mainWindow.show();

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open DevTools in dev mode
  if (process.env.MODE === 'development') {
    try {
      await installExtension([REDUX_DEVTOOLS, REACT_DEVELOPER_TOOLS]);
    } catch (error) {
      console.error('Failed to install DevTools:', error);
    }

    mainWindow.webContents.openDevTools();
  }
};

const createHelpMenu = (): void => {
  const menu = Menu.getApplicationMenu();
  if (!menu) return;

  const helpSubmenu = Menu.buildFromTemplate([
    {
      label: 'API Stories',
      click: () => shell.openExternal('https://rentgen.io/api-stories/'),
    },
    {
      label: 'GitHub Wiki',
      click: () => shell.openExternal('https://github.com/Rentgen-io/Rentgen/wiki'),
    },
    {
      label: 'Report an Issue',
      click: () => shell.openExternal('https://github.com/Rentgen-io/Rentgen/issues/new'),
    },
  ]);

  Menu.setApplicationMenu(
    Menu.buildFromTemplate(
      menu.items.map(({ label, role, submenu }) => ({
        label,
        role,
        submenu: role === 'help' ? helpSubmenu : submenu,
      })),
    ),
  );
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  cleanupLegacyStore();
  createHelpMenu();
  await createWindow();

  const settings = loadSettings();
  if (settings) nativeTheme.themeSource = settings.theme;
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) createWindow();
});

// Register handlers
registerHttpHandlers();
registerWssHandlers();
registerSettingsHandlers();
registerCollectionHandlers();
registerEnvironmentHandlers();
registerHistoryHandlers();
registerImportExportHandlers();
registerProjectHandlers();
registerCertificateHandlers();
registerCliHandlers();
registerMappingsHandlers();

ipcMain.handle('get-app-version', () => app.getVersion());
ipcMain.on('open-external', (_, url: string) => shell.openExternal(url));

// Save report
ipcMain.handle(
  'save-report',
  async (_, payload: { defaultPath?: string; content: string; filters?: Electron.FileFilter[] }) => {
    const { defaultPath = 'rentgen-report.json', content, filters } = payload || {};

    const result = await dialog.showSaveDialog({
      defaultPath,
      filters: filters ?? [{ name: 'Report', extensions: ['json'] }],
    });

    if (result.canceled || !result.filePath) return { canceled: true };

    try {
      writeFileSync(result.filePath, content, 'utf-8');
    } catch (error) {
      return { canceled: false, error: String(error) };
    }

    return { canceled: false, filePath: result.filePath };
  },
);
