import { useCallback, useEffect, useRef } from 'react';
import { useTranslation } from 'react-i18next';
import { generateCertificate as generateCertificateFile, saveReport } from 'src/api/files';
import { appConfig } from 'src/constants/appConfig';
import { useAppDispatch, useAppSelector } from 'src/store/hooks';
import { selectCurrentTestResults, selectExportFormat, selectHttpResponse } from 'src/store/selectors';
import { uiActions } from 'src/store/slices/uiSlice';
import { ExportReport, ReportFormat, ReportSuite, TestResult } from 'src/types';

const FEEDBACK_MS = 2000;
const ERROR_FEEDBACK_MS = 5000;
const MINIMUM_TESTS_FOR_CERTIFICATE = 70;

export function useReportExport() {
  const dispatch = useAppDispatch();
  const { t } = useTranslation();

  const testResults = useAppSelector(selectCurrentTestResults);
  const exportFormat = useAppSelector(selectExportFormat);
  const httpResponse = useAppSelector(selectHttpResponse);

  const exportedTimeout = useRef<ReturnType<typeof setTimeout>>(undefined);
  const certificateTimeout = useRef<ReturnType<typeof setTimeout>>(undefined);

  useEffect(
    () => () => {
      clearTimeout(exportedTimeout.current);
      clearTimeout(certificateTimeout.current);
    },
    [],
  );

  const exportReport = useCallback(async () => {
    if (!testResults) return;

    const { crudTests, dataDrivenTests, performanceTests, securityTests, testOptions } = testResults;
    const report: ExportReport = {
      generatedAt: new Date().toISOString(),
      generatedBy: appConfig.origin,
      target: {
        url: testOptions.url,
        method: testOptions.method,
        headers: testOptions.headers,
        body: testOptions.body,
      },
      lastHttpResponse: httpResponse,
      suites: [
        buildSuite('Security Tests', securityTests),
        buildSuite('Performance Insights', performanceTests),
        buildSuite('Data-Driven Tests', dataDrivenTests),
        buildSuite('CRUD', crudTests),
      ],
    };

    try {
      const result = await saveReport(formatReport(report, exportFormat));

      if (result?.error) throw new Error(result.error);
      if (result?.canceled) return;

      dispatch(uiActions.setExported(true));
      clearTimeout(exportedTimeout.current);
      exportedTimeout.current = setTimeout(() => dispatch(uiActions.setExported(false)), FEEDBACK_MS);
    } catch (error) {
      console.error('Failed to export report', error);
    }
  }, [testResults, exportFormat, httpResponse, dispatch]);

  const generateCertificate = useCallback(async () => {
    if (!testResults || testResults.count < MINIMUM_TESTS_FOR_CERTIFICATE) {
      dispatch(uiActions.setCertificateError(t('tests.notEligible')));
      clearTimeout(certificateTimeout.current);
      certificateTimeout.current = setTimeout(() => dispatch(uiActions.setCertificateError('')), ERROR_FEEDBACK_MS);
      return;
    }

    try {
      const result = await generateCertificateFile(testResults);

      if (result?.error) throw new Error(result.error);
      if (result?.canceled) return;

      dispatch(uiActions.setCertificated(true));
      clearTimeout(certificateTimeout.current);
      certificateTimeout.current = setTimeout(() => dispatch(uiActions.setCertificated(false)), FEEDBACK_MS);
    } catch (error) {
      console.error('Failed to generate certificate', error);
    }
  }, [testResults, t, dispatch]);

  return { exportReport, generateCertificate };
}

function buildSuite(name: string, tests: TestResult[]): ReportSuite {
  return {
    name,
    summary: summarizeSuite(tests),
    tests,
  };
}

function formatReport(
  report: ExportReport,
  format: ReportFormat,
): { content: string; defaultPath: string; filters: { name: string; extensions: string[] }[] } {
  const defaultPath = `rentgen-report-${new Date().toISOString().replace(/\D/g, '').slice(0, 14)}.${format}`;

  if (format === 'md')
    return {
      content: toMarkdown(report),
      defaultPath,
      filters: [{ name: 'Markdown', extensions: [format] }],
    };

  if (format === 'csv')
    return {
      content: toCsv(report),
      defaultPath,
      filters: [{ name: 'CSV', extensions: [format] }],
    };

  return {
    content: JSON.stringify(report, null, 2),
    defaultPath,
    filters: [{ name: 'JSON', extensions: [format] }],
  };
}

function summarizeSuite(tests: TestResult[]) {
  return tests.reduce(
    (acc, test) => {
      acc.total += 1;
      acc.byStatus[test.status] = (acc.byStatus[test.status] ?? 0) + 1;
      return acc;
    },
    { total: 0, byStatus: {} as Record<string, number> },
  );
}

function toMarkdown(report: ExportReport) {
  const lines: string[] = [];
  lines.push(`# Rentgen Report`);
  lines.push(`Generated at: ${report.generatedAt}`);
  lines.push(`Generated by: ${report.generatedBy}`);
  lines.push('');
  lines.push(`## Target`);
  lines.push(`- URL: ${report.target.url}`);
  lines.push(`- Method: ${report.target.method}`);
  lines.push('');

  for (const suite of report.suites) {
    lines.push(`### ${suite.name}`);
    lines.push(`- Total: ${suite.summary.total}`);
    lines.push(
      `- Statuses: ${Object.entries(suite.summary.byStatus)
        .map(([status, count]) => `${status} (${count})`)
        .join(', ')}`,
    );
    lines.push('');
    lines.push(`| Check | Expected | Actual | Status |`);
    lines.push(`| --- | --- | --- | --- |`);
    for (const test of suite.tests) {
      lines.push(
        `| ${escapeMd(test.name ?? '')} | ${escapeMd(test.expected ?? '')} | ${escapeMd(test.actual ?? '')} | ${escapeMd(test.status)} |`,
      );
    }
    lines.push('');
  }

  return lines.join('\n');
}

function toCsv(report: ExportReport) {
  const rows: string[][] = [['suite', 'check', 'status', 'expected', 'actual', 'responseTimeMs']];

  report.suites.forEach((suite) => {
    suite.tests.forEach((test) => {
      rows.push([
        suite.name,
        test.name ?? '',
        test.status,
        test.expected ?? '',
        test.actual ?? '',
        test.response?.time !== undefined ? String(test.response.time) : '',
      ]);
    });
  });

  return rows.map((row) => row.map(csvEscape).join(',')).join('\n') + `\n\nGenerated by ${report.generatedBy}`;
}

function csvEscape(value: string) {
  if (value.includes('"') || value.includes(',') || value.includes('\n')) return `"${value.replace(/"/g, '""')}"`;

  return value;
}

function escapeMd(value: string) {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}
