import { ExportReport, ReportFormat, ReportSuite, TestResult } from '../types';

export function buildSuite(name: string, tests: TestResult[]): ReportSuite {
  return {
    name,
    summary: summarizeSuite(tests),
    tests,
  };
}

export function summarizeSuite(tests: TestResult[]) {
  return tests.reduce(
    (acc, test) => {
      acc.total += 1;
      acc.byStatus[test.status] = (acc.byStatus[test.status] ?? 0) + 1;
      return acc;
    },
    { total: 0, byStatus: {} as Record<string, number> },
  );
}

export function formatReport(
  report: ExportReport,
  format: ReportFormat,
): { content: string; defaultPath: string; filters: { name: string; extensions: string[] }[] } {
  const defaultPath = `rentgen-report-${new Date().toISOString().replace(/\D/g, '').slice(0, 14)}.${format}`;

  if (format === 'md')
    return {
      content: toMarkdown(report),
      defaultPath,
      filters: [{ name: 'Markdown', extensions: [format] }],
    };

  if (format === 'csv')
    return {
      content: toCsv(report),
      defaultPath,
      filters: [{ name: 'CSV', extensions: [format] }],
    };

  return {
    content: JSON.stringify(report, null, 2),
    defaultPath,
    filters: [{ name: 'JSON', extensions: [format] }],
  };
}

function toMarkdown(report: ExportReport) {
  const lines: string[] = [];
  lines.push(`# Rentgen Report`);
  lines.push(`Generated at: ${report.generatedAt}`);
  lines.push(`Generated by: ${report.generatedBy}`);
  lines.push('');
  lines.push(`## Target`);
  lines.push(`- URL: ${report.target.url}`);
  lines.push(`- Method: ${report.target.method}`);
  lines.push('');

  for (const suite of report.suites) {
    lines.push(`### ${suite.name}`);
    lines.push(`- Total: ${suite.summary.total}`);
    lines.push(
      `- Statuses: ${Object.entries(suite.summary.byStatus)
        .map(([status, count]) => `${status} (${count})`)
        .join(', ')}`,
    );
    lines.push('');
    lines.push(`| Check | Expected | Actual | Status |`);
    lines.push(`| --- | --- | --- | --- |`);
    for (const test of suite.tests) {
      lines.push(
        `| ${escapeMd(test.name ?? '')} | ${escapeMd(test.expected ?? '')} | ${escapeMd(test.actual ?? '')} | ${escapeMd(test.status)} |`,
      );
    }
    lines.push('');
  }

  return lines.join('\n');
}

function toCsv(report: ExportReport) {
  const rows: string[][] = [['suite', 'check', 'status', 'expected', 'actual', 'responseTimeMs']];

  report.suites.forEach((suite) => {
    suite.tests.forEach((test) => {
      rows.push([
        suite.name,
        test.name ?? '',
        test.status,
        test.expected ?? '',
        test.actual ?? '',
        test.response?.time !== undefined ? String(test.response.time) : '',
      ]);
    });
  });

  return rows.map((row) => row.map(csvEscape).join(',')).join('\n') + `\n\nGenerated by ${report.generatedBy}`;
}

function csvEscape(value: string) {
  if (value.includes('"') || value.includes(',') || value.includes('\n')) return `"${value.replace(/"/g, '""')}"`;

  return value;
}

function escapeMd(value: string) {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}
